[[password]]
= BCryptPasswordEncoder加解密源码分析

[[password-overview]]
== BCryptPasswordEncoder简介

在使用 Spring Security 管理用户帐号密码的中，我们经常会用到 `BCryptPasswordEncoder` 来对密码进行加密(encode)与密码匹配(matches)。因为
`BCryptPasswordEncoder` 提供了一种强哈希算法来对密码进行加密，也就是说即使是密码相同，每次加密后的值都不相同。增强了密码的安全性。

为什么会这样？他采用的算法究竟是什么样子的？每次的密码加密后的值不同，又是如何来验证的？

bcrypt是Blowfish加密算法的一个变体，并引入了一个工作因子，允许您确定哈希函数的开销

https://codahale.com/how-to-safely-store-a-password/[How To Safely Store A Password]


[[password-principle]]
== BCryptPasswordEncoder 源码分析

`BCryptPasswordEncoder` 实现了 `PasswordEncoder` 接口。`PasswordEncoder` 接口中只有两个方法，`encode` 和 `match` 方法.

[source,java]
----
public interface PasswordEncoder {

	/**
	 * Encode the raw password. Generally, a good encoding algorithm applies a SHA-1 or
	 * greater hash combined with an 8-byte or greater randomly generated salt.
	 */
	String encode(CharSequence rawPassword);

	/**
	 * Verify the encoded password obtained from storage matches the submitted raw
	 * password after it too is encoded. Returns true if the passwords match, false if
	 * they do not. The stored password itself is never decoded.
	 *
	 * @param rawPassword the raw password to encode and match
	 * @param encodedPassword the encoded password from storage to compare with
	 * @return true if the raw password, after encoding, matches the encoded password from
	 * storage
	 */
	boolean matches(CharSequence rawPassword, String encodedPassword);

}
----

=== BCryptPasswordEncoder的构造函数:

提供了三个构造函数。客户可以选择提供 “强度”(也就是 BCrypt 的 log round)和SecureRandom的实例。强度参数越大，需要做的工作就越多(指数级)哈希密码。默认值是10。

strength：LOG ROUND这个参数大概的意思是做加密时重复处理的轮数，而且其复杂度是指数级递增，也就是传4的时候是2的4次方，默认传输为10的时候是2的10次方！其范围为4-31

SecureRandom random：这个类提供了一个加密的强随机数，其由不同的服务商提供一个伪随机数生成器。linux默认的SecureRandom实现方式是非常慢的NativePRNG，而在Windows上的默认实现是SHA1PRNG，但是你也可以在Linux上指定使用该方式。 NativePRNG 会不断从操作系统获取熵（从 `/dev/urandom` 读取），其它 PRNG 则不会获取这些额外的熵。
AESCounterRNG 差不多比 `SHA1PRNG` 快的十倍，而如果我没记错，SHA1PRNG 比 NativePRNG 快两到三倍

[source,java]
----
public BCryptPasswordEncoder() {
    this(-1);
}

public BCryptPasswordEncoder(int strength) {
    this(strength, null);
}

public BCryptPasswordEncoder(int strength, SecureRandom random) {
     //判断循环次数是否在4-31之间
    if (strength != -1 && (strength < BCrypt.MIN_LOG_ROUNDS || strength > BCrypt.MAX_LOG_ROUNDS)) {
        throw new IllegalArgumentException("Bad strength");
    }
    this.strength = strength;
    this.random = random;
}
----

=== encode加密

1.产生随机盐

2.使用 OpenBSD bcrypt 方案对密码进行哈希

[source,java]
----
public String encode(CharSequence rawPassword) {

    String salt;
    if (strength > 0) {
        if (random != null) {
            salt = BCrypt.gensalt(strength, random);
        }else {
        salt = BCrypt.gensalt(strength);
        }
    }
    else {
        salt = BCrypt.gensalt();
    }
    return BCrypt.hashpw(rawPassword.toString(), salt);
}
----

继续往下走，我们看看产生随机盐的过程。

首先会使用jre在不同环境下的SecureRandom产生一个伪随机数，也就是真实的盐，然后将算法的版本和复杂度添加到前面，以 `$` 分割。详细看源码

[source,java]
----
public static String gensalt(int log_rounds, SecureRandom random) {
    if (log_rounds < MIN_LOG_ROUNDS || log_rounds > MAX_LOG_ROUNDS) {
        throw new IllegalArgumentException("Bad number of rounds");
    }
    StringBuilder rs = new StringBuilder();
    //指定盐的为16位字节
    byte rnd[] = new byte[BCRYPT_SALT_LEN];
    //由系统产生一个伪随机数
    random.nextBytes(rnd);
    //rs=$2a$  代表了算法的版本
    rs.append("$2a$");
    if (log_rounds < 10) {
        rs.append("0");
    }
 //添加算法的复杂度
    rs.append(log_rounds);
    rs.append("$");
 //使用bcrypt的稍加修改的base64编码方案对字节数组进行编码。请注意这是并不是兼容标准MIME-base64编码。将结果返回。
    encode_base64(rnd, rnd.length, rs);
    return rs.toString();
}
----

现在盐已经生产好了，接下来就是使用盐对密码进行处理

. 首先会取出轮数，算法版本和真实的盐，并进行一系列进行校验。
. 将密码转化为字节数组。
. 对真实盐进行base64编码。请注意这是并不是兼容标准MIME-base64编码。
. 讲2，3步的结果和轮数进行哈希处理。
. 将算法版本和轮数添加到字符串rs前面，然后一起和盐和盐的长度进行一次base64编码。
. 将上一步的结果，和hash后的值，以及使用Blowfish算法的“OrpheanBeholderScryDoubt”长度*4-1进行编码。结果就是密码

[source,java]
----
public static String hashpw(String password, String salt) throws IllegalArgumentException {
BCrypt B;
 //真实的盐
String real_salt;
 //密码，盐，哈希后的值的字节码
byte passwordb[], saltb[], hashed[];
 //
char minor = (char) 0;
 //偏移量。
int rounds, off = 0;
StringBuilder rs = new StringBuilder();

if (salt == null) {
	throw new IllegalArgumentException("salt cannot be null");
}

int saltLength = salt.length();

if (saltLength < 28) {
	throw new IllegalArgumentException("Invalid salt");
}

if (salt.charAt(0) != '$' || salt.charAt(1) != '2') {
	throw new IllegalArgumentException("Invalid salt version");
}
	 //$2a$ salt.charAt(2) = 'a'
if (salt.charAt(2) == '$') {
	off = 3;
}
else {
	minor = salt.charAt(2);

	if (minor != 'a' || salt.charAt(3) != '$') {
		throw new IllegalArgumentException("Invalid salt revision");
	}
	off = 4;
}

if (saltLength - off < 25) {
	throw new IllegalArgumentException("Invalid salt");
}

// Extract number of rounds
if (salt.charAt(off + 2) > '$') {
	throw new IllegalArgumentException("Missing salt rounds");
}
rounds = Integer.parseInt(salt.substring(off, off + 2));

real_salt = salt.substring(off + 3, off + 25);
try {
	 //'\000'就是'\0'，即“空字符”可用作表示字符串结束标记。
	passwordb = (password + (minor >= 'a' ? "\000" : "")).getBytes("UTF-8");
}
catch (UnsupportedEncodingException uee) {
	throw new AssertionError("UTF-8 is not supported");
}
//将使用bcrypt的base64方案编码的字符串解码为字节数组。请注意,这与标准的MIME-base64编码不兼容。此方法有返回值，而上一步的那个没有返回值。
saltb = decode_base64(real_salt, BCRYPT_SALT_LEN);

B = new BCrypt();
 //密码，盐，轮数进行哈希
hashed = B.crypt_raw(passwordb, saltb, rounds);

rs.append("$2");
if (minor >= 'a') {
	rs.append(minor);
}
rs.append("$");
if (rounds < 10) {
	rs.append("0");
}
rs.append(rounds);
rs.append("$");
encode_base64(saltb, saltb.length, rs);
encode_base64(hashed, bf_crypt_ciphertext.length * 4 - 1, rs);
return rs.toString();
}
----

=== matches验证匹配

匹配的机制就简单多了，调用 `BCrypt.checkpw(rawPassword.toString(), encodedPassword)`;方法 ---> `equalsNoEarlyReturn(hashed, hashpw(plaintext, hashed))`; 也是调用 hashpw 方法，不同的是将旧密码当作盐传入方法中

. 首先取出旧密码中保存的盐
. 和encode的加密步骤一样。对传入的密码进行加密，返回加密结果
. 比较加密后的结果和数据库中的密码是否相同。如果相同，匹配成功