server:
  port: 19996

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: jcohy1203
  jpa:
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

