server:
  port: 9091
alpha:
  server:
    host: 0.0.0.0
    port: 9090
spring:
  application:
    name: saga-alpha-server
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.eclipse.persistence.platform.database.H2Platform
  datasource:
    url: jdbc:h2:mem:saga;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continue-on-error: false
    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
    initialization-mode: always
    type: org.apache.tomcat.jdbc.pool.DataSource
#  datasource:
#    username: saga
#    password: password
#    url: jdbc:postgresql://192.168.99.100:5432/saga?useSSL=false
#    platform: postgresql