[[go-getting-started]]
= 入门

== 安装

具体安装教程参考下面链接

https://go-zh.org/doc/install[https://go-zh.org/doc/install]

GOROOT:GOROOT就是 go 的安装路径

GOPATH:是作为编译后二进制的存放目的地和import包时的搜索路径 (其实也是你的工作目录, 你可以在src下创建你自己的go源文件, 然后开始工作)。

GOPATH之下主要包含三个目录:

* bin:主要存放可执行文件;
* pkg:存放编译好的库文件,主要是*.a文件
* src:主要存放go的源文件

[IMPORTANT]
====
不要把 GOPATH 设置成 go 的安装路径,
可以自己在用户目录下面创建一个目录, 如 gopath
====

== Hello World

====
[source, go]
----
package main <1>

import "fmt" // 实现格式化的 I/O <2>

/* Print something */ <3>
func main() { <4>
	fmt.Printf("Hello World") <5>
}
----
<1> 首行这个是必须的。所有的 Go 文件以 package <something> 开头，对于独立运行的执行文件必须是 package main；
<2> 这是说需要将fmt 包加入 main。不是 main 的其他包都被称为库。末尾以 `//` 开头的内容是注释；
<3> 这同样是注释，不过这是被包裹于 `/*` 和 `*/` 之间的；
<4> package main 必须首先出现，紧跟着是 import。在 Go 中，package 总是首先出现，然后是 import，然后是其他所有内容。当 Go 程序在执行的时候，首先调用的函数 是 main.main()，这是从 C 中继承而来。这里定义了这个函数；
<5> 调用了来自于 fmt 包的函数打印字符串到屏幕。字符串由 `"` 包裹，并且可以包含非 ASCII 的字符。
====

== 编译和运行代码

构建 go 程序的最佳途径是使用 go 工具,下面使用两种执行流程

=== 先编译，再执行
如上面的程序，要对其进行编译，只需要执行以下指令

[source, shell]
----
go build helloworld.go
----

构建的结果是 名为 helloworld 的可执行程序(windows 下是 `.exe` 文件，Linux 下是一个可执行文件)。然后运行

[source, shell]
----
./helloworld
----

=== 直接编译运行

或者我们可以直接使用 `go run` 命令编译运行，一步到位。

[source, shell]
----
go run helloworld.go
----

.两种执行流程的区别
****
* 如果我们先编译生成了可执行文件，那么我们可以将该可执行文件拷贝到没有 go 开发环境的机器上，仍然可以运行
* 如果使用 `go run` ，那么如果要在另外一台机器上使用，也需要 go 开发环境，否则无法执行
* 在编译时，编译器会将程序运行依赖的库文件包含在可执行文件中，所有，可执行文件大了许多
****

== 程序开发注意事项

. Go 源文件以 "go" 为扩展名
. Go 应用程序的执行入口是  main() 函数，这个是和其他编程语言(例如 java,c)一样。
. Go 语言严格区分大小写
. Go 方法由一条条语句构成，每个语句后面不需要分号(Go 语言会自动在每行后加分号)
. Go 编译器是一行行进行编译的，因此我们一行就写一条语句，不能把多条语句写在同一行，否则报错
. Go 语言定义的变量或者 import 的包如果没有使用到，代码不能编译通过
. 大括号都是成对出现的，不可省略

== Golang 转义符

[[go-getting-started-escape-tbl]]
.常用转义符
|===
| 转移字符 | 描述

| \t
| 表示一个制表符，通常使用他排版

| \n
| 换行符

| \\
| 一个 \

| \"
| 一个 "

| \r
| 一个回车
|===

== Golang 代码规范

* Golang 官方推荐使用行注释来注释整个方法和语句
* 正确的缩进和空白，使用 gofmt 命令进行格式化
* 运算符两边习惯各加一个空格
* 大括号必须跟在语句后面，不能单起一行。
* 一行最多不超过80个字符

== Golang 官方编程指南

官方网站: https://tour.golang.org/list[https://tour.golang.org/list]
中文网站: http://go-tour-zh.appspot.com/list[http://go-tour-zh.appspot.com/list]

== 变量,类型和关键字

与其他语言不同，在 go 语言中，变量的类型在变量名的后面。 例如，声明一个 `int` 类型的 a，是 a int , 而不是 int a.

当定义了一个变量，它默认赋值为其类型的 `null` 值，例如，在 var a int 后， `a` 的值为 `0`, 而 var s String ，`s` 为零长度字符串。也就是 `""`

在 Go 中，声明和赋值是两个过程