[[go-module]]
= go 模块

Go `1.11` 和 `1.12` 包含对模块的初步支持, 该模块是Go的新依赖管理系统, 该系统使依赖版本信息明确且易于管理. 在 Go `1.14` 中, Go 的模块支持已经可以用于生产环境, 并且鼓励所有用户从其他依赖项管理系统迁移到模块依赖管理. 如果由于 Go 工具链中的问题而无法迁移, 请确保该问题已 https://github.com/golang/go/wiki/Modules#github-issues[公开].

模块是存储在文件树中的 Go 软件包的集合, 其根目录中有 `go.mod` 文件.  `go.mod` 文件定义模块的模块路径(这也是用于根目录的导入路径)及其依赖关系要求, 它们是构建所依赖的其他模块.  每个依赖都要求都写为模块路径和特定的语义版本.

从 Go 1.11 开始, 当当前目录或任何父目录具有 `go.mod` 时, 只要该目录位于 `$GOPATH/src` 之外, go 命令就可以使用模块.  (在 `$GOPATH/src` 内部, 出于兼容性考虑, 即使找到了 `go.mod`, go 命令仍然在旧的 GOPATH 模式下运行. 有关详细信息, 请参见 https://golang.org/cmd/go/#hdr-Preliminary_module_support[go 命令文档]. )从 Go 1.13 开始, 模块模式将是默认模式.

[[go-module-create]]
== 创建一个模块

在  `$GOPATH/src` 之外的新创建一个目录, 然后创建一个新文件 hello.go

[source,go]
----
package hello

func Hello() string {
    return "Hello, world."
}
----

创建此方法的测试文件

[source,go]
----
package hello

import "testing"

func TestHello(t *testing.T) {
    want := "Hello, world."
    if got := Hello(); got != want {
        t.Errorf("Hello() = %q, want %q", got, want)
    }
}
----

到目前为止, 此目录包含了一个包, 但并没有模块, 因为不存在 `go.mod` 文件, 如果执行 `go test` 命令, 会出现下面的错误

====
[source,shell]
----
D:\workspacce\GoWorkspace\hello> go test
PASS
ok  	_/D_/workspacce/GoWorkspace/hello	0.020s <1>
----
<1> 这一行总结整个包的测试情况, 因为我们在 `$GOPATH` 之外的目录工作, 所以 go 命令不知道当前目前的导入情况, 而是根据目录名生成的一个 `_/D_/workspacce/GoWorkspace/hello` 目录
====

让我们使用 `go mod init` 将当前目录设为模块的根目录, 然后再次尝试 `go test`:

[source,shell]
----
D:\workspacce\GoWorkspace\hello> go mod init example.com/hello
go: creating new go.mod: module example.com/hello
D:\workspacce\GoWorkspace\hello> go test
PASS
ok  	example.com/hello	0.020s
----

恭喜你！ 您已经编写并测试了第一个模块.

`go mod init` 命令编写了一个 `go.mod` 文件:

[source,go]
----
module example.com/hello

go 1.14
----

`go.mod` 文件仅出现在模块的根目录中.  子目录中的程序包由模块路径以及子目录路径组成.  例如, 如果我们创建了一个子目录 `world`, 不用在那里运行 `go mod init`.  该软件包将自动被识别为 `example.com/hello` 模块的一部分, 导入路径为 `example.com/hello/world`.

[[go-module-dependency]]
== 依赖管理

[[go-module-dependency-download]]
=== 下载依赖

Go 模块的主要目标是为了改善使用其他开发人员编写的代码(即添加对代码的依赖)的体验.  让我们更新 `hello.go` 以导入 `rsc.io/quote` 并使用它来实现 `Hello`:

[source,go]
----
package hello

import "rsc.io/quote"

func Hello() string {
    return quote.Hello()
}
----

然后再执行测试

[source,shell]
----
D:\workspacce\GoWorkspace\hello> go test
go: finding rsc.io/quote v1.5.2
go: downloading rsc.io/quote v1.5.2
go: extracting rsc.io/quote v1.5.2
go: finding rsc.io/sampler v1.3.0
go: finding golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: downloading rsc.io/sampler v1.3.0
go: extracting rsc.io/sampler v1.3.0
go: downloading golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
go: extracting golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
PASS
ok  	example.com/hello	0.023s
----

[NOTE]
====
从 go 1.13 开始, go 工具默认是从 `https://proxy.golang.org` 上的公共 Go 模块镜像下载模块, 并且还默认使用 `https://sum.golang.org` 数据库来校验下载的模块. 在下载模块的时候, 可能导致会失败. 请参考此 <<go-module-goproxy>> 修改 goproxy
====

go 命令会自动解析 `go.mod` 中列出的特定依赖模块版本并导入.  当程序中导入未由 `go.mod` 提供的模块时, go 命令将自动使用  `latest` 版本查找包含该软件包的模块, 并将其添加到 `go.mod` 中.  (“Latest” 定义为最新的稳定 Tag(非预发行)版本, 或者最新的预发行版本 Tag, 或者最新的非 Tag 版本. ).
在我们的示例中, `go test` 将新的导入 `rsc.io/quote` 解析为 `rsc.io/quote v1.5.2` 模块 它还下载了 `rsc.io/quote` 使用的两个依赖项, 即 `rsc.io/sampler` 和 `golang.org/x/text`.  go.mod文件中仅记录直接依赖项:

go.mod 文件内容如下

[source,go]
----
module example.com/hello

go 1.14

require rsc.io/quote v1.5.2
----

第二次执行 `go test` 命令时不会重复下载依赖, 因为 `go.mod` 现在是最新的, 并且下载的模块已本地缓存(在 `$GOPATH/pkg/mod` 中)

[NOTE]
====
请注意, 尽管 go 命令使添加新的依赖关系变得快速而轻松, 但这并非没有代价.  您的模块看起来添加了一个新的依赖, 但对依赖包的正确性, 安全性和适当的许可等不得而知.  有关更多注意事项, 请参阅 Russ Cox 的博客文章 https://research.swtch.com/deps[“Our Software Dependency Problem.“].
====

正如我们在上面看到的, 添加一个直接依赖项通常也会带来其他间接依赖项. 命令 `go list -m all` 列出当前模块及其所有依赖项:

[source,go]
----
go list -m all
example.com/hello
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c
rsc.io/quote v1.5.2
rsc.io/sampler v1.3.0
----

在 go 列表输出中, 当前模块(也称为主模块)总是第一行, 后面是按模块路径排序的依赖项.

`golang.org/x/text` 版本是 `v0.0.0-20170915032832-14c0d48ead0c` , 这是一个 https://golang.org/cmd/go/#hdr-Pseudo_versions[pseudo-version]的例子, 它是 go 命令用于特定未标记提交的版本语法.

除了 `go.mod` 之外, go命令还会维护一个名为 `go.sum` 的文件, 其中包含特定模块版本内容的预期的 https://golang.org/cmd/go/#hdr-Module_downloading_and_verification[cryptographic hashes]:

go.sum 文件内容

[source,shell]
----
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c h1:qgOY6WgZOaTkIIMiVjBQcw93ERBE4m30iBm00nkL0i8=
golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c/go.mod h1:NqM8EUOU14njkJ3fqMW+pc6Ldnwhi/IjpwHt7yyuwOQ=
rsc.io/quote v1.5.2 h1:w5fcysjrx7yqtD/aO+QwRjYZOKnaM9Uh2b40tElTs3Y=
rsc.io/quote v1.5.2/go.mod h1:LzX7hefJvL54yjefDEDHNONDjII0t9xZLPXsUe+TKr0=
rsc.io/sampler v1.3.0 h1:7uVkIFmeBqHfdjD+gZwtXXI+RODJ2Wc4O7MPEh/QiW4=
rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
----

go 命令使用 `go.sum` 文件来确保这些模块的将来下载与第一次下载时检索位相同, 以确保您的项目所依赖的模块不会由于恶意, 意外或其他原因而意外更改.  应该将 `go.mod` 和 `go.sum` 都添加到版本控制中.

[[go-module-dependency-update]]
=== 更新依赖

对于 Go 模块, 版本号使用语义版本标记.  语义版本包括三个部分: `major`, `minor` 和 `patch`.  例如, 对于 `v0.1.2`, `major` 版本为 `0`, `minor` 版本为 `1`, `patch` 版本为 `2`. 让我们逐步进行几个 `minor` 版本升级.  在下一节中, 我们将考虑进行 `major` 版本升级.

[[go-module-dependency-update-minor]]
==== 更新 minor 版本

从 `go list -m all` 的输出中, 我们可以看到我们正在使用未标记版本的 `golang.org/x/text`.  让我们升级到最新的标记版本, 并测试一切是否正常:

[source,shell]
----
go get golang.org/x/text
go: finding golang.org/x/text v0.3.0
go: downloading golang.org/x/text v0.3.0
go: extracting golang.org/x/text v0.3.0

go test
PASS
ok  	example.com/hello	0.013s
----

让我们再来看一下 `go list -m all` 和 `go.mod` 文件:

[source,go]
----
go list -m all
example.com/hello
golang.org/x/text v0.3.0
rsc.io/quote v1.5.2
rsc.io/sampler v1.3.0

cat go.mod
module example.com/hello

go 1.14

require (
    golang.org/x/text v0.3.0 // indirect
    rsc.io/quote v1.5.2
)
----

`golang.org/x/text` 软件包已升级到最新的标记版本(`v0.3.0`).  `go.mod` 文件也已更新为指定 `v0.3.0`.  `indirect` 注释指示此模块不直接使用依赖关系, 而是由其他模块间接依赖.  有关详细信息, 请参阅 `go help modules` .

现在, 让我们尝试升级 `rsc.io/sampler` 次要版本.  通过运行 `go get` 和执行测试:

[source,go]
----
go get rsc.io/sampler
go: finding rsc.io/sampler v1.99.99
go: downloading rsc.io/sampler v1.99.99
go: extracting rsc.io/sampler v1.99.99

go test
--- FAIL: TestHello (0.00s)
    hello_test.go:8: Hello() = "99 bottles of beer on the wall, 99 bottles of beer, ...", want "Hello, world."
FAIL
exit status 1
FAIL	example.com/hello	0.014s
----

测试失败表明 `rsc.io/sampler` 的最新版本与我们的用法不兼容. 让我们列出该模块的可用标记版本:

[source,shell]
----
go list -m -versions rsc.io/sampler
rsc.io/sampler v1.0.0 v1.2.0 v1.2.1 v1.3.0 v1.3.1 v1.99.99
----
我们一直在使用 `v1.3.0`; `v1.99.99` 显然不好. 也许我们可以尝试使用 `v1.3.1` 代替:

[source,shell]
----
go get rsc.io/sampler@v1.3.1
go: finding rsc.io/sampler v1.3.1
go: downloading rsc.io/sampler v1.3.1
go: extracting rsc.io/sampler v1.3.1

go test
PASS
ok  	example.com/hello	0.022s
----

[NOTE]
====
请注意 `go get` 参数中的显式 `@ v1.3.1`. 通常, 传递给 get 的每个参数都可以采用显式形式. 默认值为 `@latest`, 它将解析为先前定义的最新版本.
====

[[go-module-dependency-update-major-add]]
==== 添加一个新的 major 版本依赖

让我们在包中添加一个新函数: `func Proverb` 通过调用 `quote.Concurrency` 返回 Go concurrency proverb, 这是由 `rsc.io/quote/v3` 模块提供的. 首先, 我们更新 `hello.go` 以添加新功能

[source,go]
----
package hello

import (
    "rsc.io/quote"
    quoteV3 "rsc.io/quote/v3"
)

func Hello() string {
    return quote.Hello()
}

func Proverb() string {
    return quoteV3.Concurrency()
}
----

添加测试

[source,go]
----
package hello

import "testing"

func TestHello(t *testing.T) {
    want := "Hello, world."
    if got := Hello(); got != want {
        t.Errorf("Hello() = %q, want %q", got, want)
    }
}

func TestProverb(t *testing.T) {
    want := "Concurrency is not parallelism."
    if got := Proverb(); got != want {
        t.Errorf("Proverb() = %q, want %q", got, want)
    }
}
----

然后测试代码

[source,shell]
----
go test
go: finding rsc.io/quote/v3 v3.1.0
go: downloading rsc.io/quote/v3 v3.1.0
go: extracting rsc.io/quote/v3 v3.1.0
PASS
ok  	example.com/hello	0.024s
----

请注意, 我们的模块现在同时依赖 `rsc.io/quote` 和 `rsc.io/quote/v3`:

[source,shell]
----
go list -m rsc.io/q...
rsc.io/quote v1.5.2
rsc.io/quote/v3 v3.1.0
----

Go 模块的每个不同的 `major` 版本(`v1`, `v2` 等)都使用不同的模块路径: 从 `v2` 开始, 该路径必须以主要版本结尾.  在示例中, `rsc.io/quote` 的 `v3` 不再是 `rsc.io/quote`: 而是由模块路径 `rsc.io/quote/v3` 标识.
此约定称为 https://research.swtch.com/vgo-import[语义导入版本], 它为不兼容的程序包(具有不同主要版本的程序包)提供了不同的名称.  相反, `rsc.io/quote` 的 `v1.6.0` 应该与 `v1.5.2` 向后兼容, 因此它重用了名称 `rsc.io/quote`.
(在上一节中, `rsc.io/sampler v1.99.99` 应该已经与 `rsc.io/sampler v1.3.0` 向后兼容, 但是关于模块行为的错误或错误的客户端假设都可能发生. )

go 命令允许构建最多包含任何特定模块路径的一个版本, 即每个 `major` 版本: 一个 `rsc.io/quote`, 一个 `rsc.io/quote/v2`, 一个 `rsc.io/quote/ v3`, 依此类推.
这为模块作者提供了关于可能重复单个模块路径的明确规则: 程序无法同时使用 `rsc.io/quote v1.5.2` 和 `rsc.io/quote v1.6.0` 来构建.  同时, 允许模块的不同主要版本(因为它们具有不同的路径)使模块使用者可以逐步升级到新的主要版本.
在此示例中, 我们想使用 `rsc/quote/v3 v3.1.0` 中的 `quote.Concurrency`, 但尚未准备好迁移 `rsc.io/quote v1.5.2` 的使用.  在大型程序或代码库中, 增量迁移的能力尤其重要.

[[go-module-dependency-update-major]]
==== 更新 major 版本

让我们完成从使用 `rsc.io/quote` 到仅使用 `rsc.io/quote/v3` 的转换.  由于版本的重大更改, 我们应该期望某些 API 可能已以不兼容的方式被删除, 重命名或以其他方式更改.  阅读文档, 我们可以看到 `Hello` 已经变成 `HelloV3`:

[source,shell]
----
go doc rsc.io/quote/v3
package quote // import "rsc.io/quote"

Package quote collects pithy sayings.

func Concurrency() string
func GlassV3() string
func GoV3() string
func HelloV3() string
func OptV3() string
----

[IMPORTANT]
====
输出中还存在一个已知的错误;显示的导入路径错误地删除了/v3.
====

我们可以在 `hello.go` 中更新对 `quote.Hello()` 的使用, 以使用 `quoteV3.HelloV3()`:

[source,go]
----
package hello

import quoteV3 "rsc.io/quote/v3"

func Hello() string {
    return quoteV3.HelloV3()
}

func Proverb() string {
    return quoteV3.Concurrency()
}
----

然后在这一点上, 不再需要重命名的导入, 因此我们可以撤消该操作:

[source,go]
----
package hello

import "rsc.io/quote/v3"

func Hello() string {
    return quote.HelloV3()
}

func Proverb() string {
    return quote.Concurrency()
}
----

让我们重新运行测试以确保一切正常:

[source,shell]
----
go test
PASS
ok      example.com/hello       0.014s
----

[[go-module-dependency-delete]]
=== 删除未使用的依赖项

我们已经删除了对 `rsc.io/quote` 的所有使用, 但是它仍然显示在 `go list -m all` 和 `go.mod` 文件中:

[source,shell]
----
go list -m all
example.com/hello
golang.org/x/text v0.3.0
rsc.io/quote v1.5.2
rsc.io/quote/v3 v3.1.0
rsc.io/sampler v1.3.1

cat go.mod

module example.com/hello

go 1.14

require (
    golang.org/x/text v0.3.0 // indirect
    rsc.io/quote v1.5.2
    rsc.io/quote/v3 v3.0.0
    rsc.io/sampler v1.3.1 // indirect
)
----

为什么？ 因为像 `go build` 或 `go test` 这样构建单个程序包可以轻松判断何时缺少某些内容并需要添加, 但是无法确定何时可以安全删除.  仅在检查模块中的所有软件包以及这些软件包的所有可能的构建标记组合之后, 才能删除依赖项.  普通的 `build` 命令不会加载此信息, 因此它不能安全地删除依赖项.

`go mod tidy` 命令清除了这些未使用的依赖项:

[source,shell]
----
go mod tidy

go list -m all
example.com/hello
golang.org/x/text v0.3.0
rsc.io/quote/v3 v3.1.0
rsc.io/sampler v1.3.1
$ cat go.mod
module example.com/hello

go 1.14

require (
    golang.org/x/text v0.3.0 // indirect
    rsc.io/quote/v3 v3.1.0
    rsc.io/sampler v1.3.1 // indirect
)

go test
PASS
ok  	example.com/hello	0.020s
----

[[go-module-dependency-result]]
=== 结论

Go 模块是 Go 中依赖管理的未来.  现在, 所有受支持的 Go 版本(即 `Go 1.11` 和 `Go 1.12`)都提供模块功能.

* `go mod init` 创建一个新模块, 初始化描述它的go.mod文件.
* `go build`, `go test` 和其他程序包构建命令根据需要向 `go.mod` 添加新的依赖项.
* `go list -m all` 打印当前模块的依赖关系.  去获取更改所需的依赖版本(或添加新的依赖)
* `go mod tidy` 删除未使用的依赖项.

https://blog.golang.org/using-go-modules[参考文档]

[[go-module-migrating]]
== 合并至 Go module

https://blog.golang.org/migrating-to-go-modules[参考文档]

[[go-module-publish]]
== 发布 Go module

https://blog.golang.org/publishing-go-modules[参考文档]

[[go-module-v2]]
== Go模块: v2及更高版本

https://blog.golang.org/v2-go-modules[参考文档]

[[go-module-goproxy]]
== 修改 Goproxy

目前发现的几个不错的 goproxy

* 阿里云
+
export GOPROXY=https://mirrors.aliyun.com/goproxy/
* nexus社区提供的
+
export GOPROXY=https://gonexus.dev
* 七牛云赞助支持的
+
export GOPROXY=https://goproxy.cn
* 官方提供的(jfrog,golang)
+
export GOPROXY=https://gocenter.io
+
export GOPROXY=https://proxy.golang.org
* 基于athens的公共服务
+
export GOPROXY=https://athens.azurefd.net
* goproxy.io 的
+
export GOPROXY=https://goproxy.io/

在 GOPROXY 环境变量现在可以设置为逗号分隔的列表. 它会在回到下一个路径之前尝试第一个代理.

GOPROXY 的默认值为 `https://proxy.golang.org,direct`. 设置 direct 后将忽略之后的所有内容. 这也意味着 go get 现在将默认使用 GOPROXY . 如果你根本不想使用 GOPROXY, 则需要将其设置为 off.

新版本将引入了一个新的环境变量 GOPRIVATE , 它包含以逗号分隔的 全局列表. 这可用于绕过 GOPROXY 某些路径的代理, 尤其是公司中的私有模块(例如: `GOPRIVATE=*.internal.company.com`).