[[go-package]]
= 包

包是函数和数据的集合,用 `package` 关键字定义一个包.go 的每一个文件都是属于一个包的.也就是说 go 是通过以包的形式来管理文件和项目目录结构的.

* 文件名不需要与包名一致
* 包名的约定是使用小写字符
* 包可以由多个文件组成

[[go-package-usage]]
== 包的三大作用

. 区分相同名字的函数,变量,标识符
. 当程序文件很多时,可以很好的管理项目
. 控制函数,变量等访问范围,即作用域

[[go-package-grammer]]
== 包的语法

打包:

[source,go]
----
package 包名
----

引入包:

[source,go]
----
import "包的路径"
----

引入多个包

[source,go]
----
import (
	"包的路径"
)
----

[[go-package-notice]]
== 注意事项

. `package` 指令在文件的第一行,然后是 import 指令
. 在 `import` 包时,路径从 `$GOPATH` 的 `src` 下开始,不用带 `src` ,编译器会自动从 `src` 下开始引入
. 为了让其他包的文件可以访问到本包的函数,则该 **函数名的首字母需要大写** 类似其他语言的 public ,这样才能跨包访问.
. 在访问其他包函数,变量时,其语法是 包名.函数名
. 如果包的名称过厂,Go 支持给包取别名,**注意:取别名后,原来的包名就不能使用了**
. 在同一个包下,不能有重复的函数名,全局变量名.
. 如果你要编译成一个可执行程序文件,就需要将这个包声明为 `main`,即 `package main` 这个就是一个语法规范,如果你是写一个库,包名可以自定义

[[go-package-docs]]
== 包的文档

每个包都应该有包注释,在 `package` 钱的一个注释块,对于多文件包,包注释只需要出现在一个文件前,任意一个文件都可以,包注释应当对包进行介绍,并提供相关于包的整体信息.
这会出现在 `go doc` 生成的关于包的页面上.如下

首先定义一个包,然后编写一个函数.有关函数的相关信息,请参见<<go-function>>

.src/jcohy/utils.go
====
[source,go]
----
/*
The pacakge is provide some utils <1>

 */
package jcohy <2>

// 交换两个数的值
func Swap(a,b *int) { <3>
	t := *a
	*a = *b
	*b = t
}

func Even(a int) bool { <4>
	return a % 2 ==0
}
----
<1> 包文档注释
<2> 定义包名为 jcohy
<3> 定义一个函数,用来交换两个数的值.注意函数名首字母大写,这样别的包才可以访问到
<4> 判断是不是偶数,用于下一节对包的测试
====

包的使用:

.src/main/main.go
====
[source,go]
----
package main

import (
	"fmt"
	"jcohy" <1>
)

func main(){
	x,y := 1,2
	jcohy.Swap(&x,&y) <2>
	fmt.Printf("x = %d,y=%d\n ",x,y) // <3>
}
----
<1> 引入我们刚才定义好的包
<2> 执行函数
<3> 输出结果为 x = 2,y=1
====

[[go-package-test]]
== 测试包

在 Go 中为包编写单元测试应当是一种习惯,编写测试需要包含 `testing` 包和程序 `go test`.

`go test` 程序调用了所有的测试函数,jcohy 包中没有定义任何测试函数,执行 go test,结果如下

[source,shell]
----
D:\workspacce\awesomeProject\src\jcohy>go test
?       jcohy   [no test files]
----

我们接下来定义一个测试,测试文件也在包目录中,被命名为 `*_test.go` .这些测试文件和 Go 程序中的其他文件一样,但是 `go test` 只会执行测试函数,每个测试函数都有相同的标识,它的名字以 `Test` 开头

[source,go]
----
func TestXxx(*testing.T)
----

关于测试结果处理,可以使用以下函数标记

[[go-package-test-tbl]]
.测试结果处理
|===
| 方法 | 描述

| func (t *T) Fail() | Fail 标记测试函数失败,但仍然继续执行

| func (t *T) FailNow() | FailNow 标记测试函数失败,并且中断其执行,当前文件中的其余测试将被跳过,然后执行下一个文件中的测试

| func (t *T) Log(args ...interface{}) | Log 用默认格式对其参数进行格式化,与 Print() 类似,并且记录文本到错误日志

| func (t *T) Fatal(args ...interface{}) | Fatal 等价于 Log() 后跟随 FailNow()
|===

接下来我们就可以对包进行测试了,以上一节定义的包为例,对其 `Even` 函数进行测试.我们在

.src/jcohy/utils_test.go
====
[source,go]
----
package jcohy <1>

import (
	"testing" <2>
)

func TestEven(t *testing.T) { <3>
	if !Even(2){
		t.Log("2 should be even !")
		t.Fail()
	}
}

----
<1> 包名与被测试的包名字相同
<2> 导入 `testing` 包
<3> 定义测试函数
====

然后我们执行 `go test` ,会得到加入输出.

[source,shell]
----
D:\workspacce\awesomeProject\src\jcohy>go test
PASS
ok      jcohy   0.253s
----

重新定义测试函数,就可以得到一个失败的案例

.src/jcohy/utils_test.go
====
[source,go]
----
package jcohy <1>

import (
	"testing" <2>
)

func TestEven(t *testing.T) { <3>
	if Even(2){
		t.Log("2 should be even !")
		t.Fail()
	}
}

----
<1> 包名与被测试的包名字相同
<2> 导入 `testing` 包
<3> 定义测试函数
====

然后得到:

[source,shell]
----
D:\workspacce\awesomeProject\src\jcohy>go test
--- FAIL: TestEven (0.00s)
    utils_test.go:9: 2 should be even !
FAIL
exit status 1
FAIL    jcohy   0.267s
----

单元测试注总结

. 测试用例文件必须以 `_test.go` 结尾
. 测试用例函数必须以 `Test` 开头,一般来说就是 Test+被测试的函数名
. 一个测试用例文件中,可以有多个测试用例函数
. 运行测试用例指令 `go test`,  `go test -v`
. 当出现错误时,可以使用 t.Fatalf 来格式化输出错误信息,并退出程序
. `t.Logf` 方法可以输出相应的日志
. 测试单个文件,一定要带上被测试的源文件.例如 `go test -v cal_test.go cal.go`

[[go-package-usuall]]
== 常用的包

Go 语言的标准库包含了大量的包,并且会在安装 Go 时会伴随一起安装.可以在 `$GOPATH/src/pkg` 下找到.下面列出了一些常用的包

[[go-package-usuall-tbl]]
.常用的包
|===
| 包 | 描述

| fmt | fmt 实现了格式化的 I/O 函数,格式化短语派生于 C

| io | io 这个包提供了原始的 I/O 操作界面.主要的任务是对 os 包这样的原始的额 I/O 进行封装,增加了一些其他相关,使其具有抽象功能用在公共的接口上

| bufio | bufio 这个包实现了缓冲 I/O .它封装于 `io.Reader` 和 `io.Writer` 对象,创建了另一个对象(`Reader` 和 `Writer`)在提供缓冲的同时实现了一些文本 I/O 的功能

| sort | sort 包提供了对数组和用户定义集合的原始的排序功能

| strconv | strconv 包提供了将字符串转换成基本数据类型,或者从基本数据类型转换为字符串

| os | os 包提供了与平台无关的操作系统功能接口,其设计是 Unix 形式的

| sync | sync 包提供了基本的同步原语,例如 互斥锁

| flag | flag 包实现了命令行解析

| encoding/json | encoding/json 包实现了编码与解码

| html/template | 数据驱动模板,用于生成文本的输出,例如 HTML

| net/http | net/http 实现了 HTTP 请求,响应和 URL 解析,并且提供了可扩展的 HTTP 服务和基本的 HTTP 客户端

| unsafe | unsafe 包包含了 Go 程序中数据类型上所有不安全的操作.通常无需使用这个

| reflect | reflect 包实现了运行时反射,允许程序通过抽象类型操作对象.通常用于处理静态类型 `interface{}` 的值,并且通过 `Typeof` 解析出其动态类型信息,通常会返回一个有接口类型 `Type` 的对象

| os/exec | os/exec 包执行外部命令
|===